language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25

# installing Java 8 JDK is required to prevent getting "Unsupported major.minor version 52.0" error
jdk:
  - oraclejdk8

script:
  ./gradlew clean check --stacktrace --no-daemon

sudo:
  false

notifications:
  email: false