language: android

# installing Java 8 JDK is required to prevent getting "Unsupported major.minor version 52.0" error
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.0
    - android-25

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'

script:
  - ./gradlew clean check --stacktrace --no-daemon
  - ./gradlew build jacocoTestReport assembleAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo:
  false

notifications:
  email: false